/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package queue.core;
import spark.Spark;
import spark.Request;
import static spark.Spark.get;
import static spark.Spark.put;

public class App {
    public String getGreeting() {
        return "Hello fede!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        get("/ping",(req, res) -> renderTodos(req));
        put("/pim",(req, res) -> renderTodos(req));
    }
    private static String renderTodos(Request req) {
        return "pong";
    }
    }

