/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package queue.core;

import spark.Request;

import static spark.Spark.get;

public class App {
    public String getGreeting() {
        return "Hello fede!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        get("/ping", (req, res) -> buildAnswer(req));
    }

    private static String buildAnswer(Request req) {
        return "pong";
    }
}
